travis:
  secure:
    BINSTAR_TOKEN: gTHxQh3L/BM1xfF4kZ33WQ6rt4UEQqH5OgL5FYe2JHdJSCxBL/ro4Dvg/95i9acVJFQGN+icTuCFKEwTV0pYQVdJWT2QYFOu+Oa11COOlHR4xPf4+hyrEPbPkgOiRZ5fjvNOwwohz+O9DOVpb+IxI5qJvInLaZZA/ruhBYCesg8Ymd4zP7cgh3Cb+cuhMLhfEv+4LH7OoWsG2tRE/R1evYimm06wUWzE04xCQuzWvQa+3FLl2IRaAd5Al+X9qEIdheYjMV/a11RZs2yvYi3GdCssL4D9gRisK8wiLVNM0vkGYXh4g4SgnrOMcXiwuB0Lz6XX66q0v2NY9geQpSnnwko89+zzHZlYgSSCv9YvM6dM42tM1q7LKGl7tB6rQsapit0BF6Bu/IXuOHPZtqNVChf2JXz5Z/DutIBpyetGxT6ihJ7Oab5IIir6yJXoReeeurjAKCNansQqZrrDIJYmKgccby3VGIW5zNs22RlRm6GMQ7BJL38kmzGnfywm06KKsYS1EQXPtTIMpGYl53q5p/eah9nP0292FeLMoaAl0tKj8/f2zkWScnOnifb2ZY/TRdp6Cu+xEQNcEMEWW/mI9xyPolV2Dro2bcwNr5A0PS1ExwZDlzrbj3DBDYMjFp8aAlvjkr4IDBsZfoEqimb4j8TAElFSX45+laqGqLl7b5o=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
