travis:
  secure:
    BINSTAR_TOKEN: mbAsNkI8T60rDGESGoYbGXsHFqNP7+ke3SqHT+YufVQ+l1VUkYJu6F8gIrEU5hNIIs5cMiDSeMP3Bku1/geJ2HpfITDtgt5yrmhPvEw8f47NwEXAcCA64FWdZ9dC4Gm+/G6xdYIOmDMJjga66QAN/C5ji2kKhh+d6FK6vMEawsasWA44Ikri6cb0gOlIWhUvWXf6tKlpw2LDIR7RVTq2Ye73f6q8qRvP0oWbIq1amWoJOeQHPVIIf+2GZ/21t440cs0/E5vsgBET7Cdno0OmemrQdpjhW/s1OarQamqnjC0oTAP89BbRHW8Rd9MDZITz/eLLFLFop7Q1IQh4/xAggWIbdLLiJIl5Ze/tTQhUfpnZOs/hPXQfx1wCSphFMGfizgeCUtzFMd1CnVzOTdK0AQMvT+ui3pd80fz8mVCQHt8HzzyQA01rnRUGo+EbQLMsb132V+VJO2/OfKcZXUAP2dKEeY45//j5g6Xqwg98S1y7LC7eTXsecYPodRkJzbKJLi2Ncv6ZIY8OuDNTKYBCMBwI7FyAnYCVEtUedNzhZSaBYQWM7rUzZVbmoxVNYsNbigtOmfFWN55h2FtC9aIdQwajFQmE4Rykf7C9d0/6E27DQcjMQ2GyAMD/5xL6E9VxeMnug33EGZBHngL4R8QNSTksBwbh607GcxT4t/eg0Wc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
